version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: sunday
  open-pull-requests-limit: 10
  assignees:
  - g-bastianelli
  labels:
  - bump
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-react"
    versions:
    - 7.10.4
    - 7.12.13
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.1
  - dependency-name: rollup
    versions:
    - 2.32.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: eslint-plugin-react
    versions:
    - 7.20.5
  - dependency-name: elliptic
    versions:
    - 6.5.3
